# Generated by Django 4.2.1 on 2023-06-09 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(default='こんにちわ。よろしくお願いします', max_length=200)),
                ('emailField', models.EmailField(max_length=255)),
                ('userimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('postimage', models.ImageField(upload_to='')),
                ('day', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
