# Generated by Django 4.2.1 on 2023-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('amineid', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('related', models.CharField(max_length=200)),
                ('animeimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pracename', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('acsess', models.CharField(max_length=150)),
                ('praceimage', models.ImageField(upload_to='')),
                ('postid', models.IntegerField(max_length=100)),
                ('animeid', models.IntegerField(max_length=100)),
            ],
        ),
    ]
