# Generated by Django 4.2.1 on 2023-06-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anime_prace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prace',
            name='animeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anime'),
        ),
        migrations.AlterField(
            model_name='prace',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
