# Generated by Django 4.2.1 on 2023-06-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_prace_animeid_alter_prace_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='userid',
        ),
    ]
