# Generated by Django 4.2.1 on 2023-06-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_post_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prace',
            name='postid',
        ),
        migrations.AddField(
            model_name='post',
            name='praceid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.prace'),
            preserve_default=False,
        ),
    ]
